# Runs all galleries against staging
name: Test Staging
on:
  pull_request_target:
    branches:
      - master

jobs:
  test-staging:
    runs-on: ubuntu-latest
    # TODO: If GitHub gives access to the commit message in PRs, this gets easier.
    # if: "contains(github.event.head_commit.message, 'test-staging')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: get commit message
        run: |
           echo 'COMMIT_MESSAGE<<EOF' >> $GITHUB_ENV
           echo "$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
           echo 'EOF' >> $GITHUB_ENV

      - name: Update Submodules
        if: contains( env.COMMIT_MESSAGE , 'test-staging' )
        run: git submodule update --init --recursive --remote

      - uses: actions/setup-python@v1
        if: contains( env.COMMIT_MESSAGE , 'test-staging' )
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Dependencies
        if: contains( env.COMMIT_MESSAGE , 'test-staging' )
        run: |
          pip install -r requirements.txt

      - name: Run staging
        if: contains( env.COMMIT_MESSAGE , 'test-staging' )
        run: |
          python .github/workflows/scripts/run_staging.py
